services:
  - type: web
    name: anachak-kasekor-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_bot.py
    envVars:
      - key: MAIN_BOT_TOKEN
        sync: false
      - key: SOIL_BOT_USERNAME
        value: detect_soil_bot
      - key: RICE_SEED_BOT_USERNAME
        value: detect_rice_seed_bot
      - key: RICE_DISEASE_BOT_USERNAME
        value: detect_leaf_of_rice_bot
      - key: WEATHER_BOT_USERNAME
        value: detect_weather_bot
      - key: MARKET_BOT_USERNAME
        value: cambomarket_bot
      - key: CHATBOT_USERNAME
        value: cambochatAI_bot
